services:
  mysql:
    image: mysql:8.0
    container_name: bodeum-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bodeum
    volumes:
      - bodeum-mysql-data:/var/lib/mysql

volumes:
  bodeum-mysql-data:
