-- info_item 테이블의 문자열/주소 관련 컬럼 NULL 허용
ALTER TABLE info_item MODIFY COLUMN address VARCHAR(255) NULL;
ALTER TABLE info_item MODIFY COLUMN sido VARCHAR(50) NULL;
ALTER TABLE info_item MODIFY COLUMN sigungu VARCHAR(50) NULL;
ALTER TABLE info_item MODIFY COLUMN phone VARCHAR(50) NULL;
ALTER TABLE info_item MODIFY COLUMN homepage_url VARCHAR(500) NULL;
ALTER TABLE info_item MODIFY COLUMN image_url VARCHAR(500) NULL;
ALTER TABLE info_item MODIFY COLUMN introduction TEXT NULL;